WITH first_ok AS (
  SELECT m.SYMBOL, DATEADD(day,14,MIN(m.TRADE_DATE)) AS START_OK
  FROM MARKET_OHLCV m
  GROUP BY m.SYMBOL
),
cal AS (
  SELECT m.SYMBOL, m.TRADE_DATE
  FROM MARKET_OHLCV m
  JOIN first_ok f ON f.SYMBOL=m.SYMBOL AND m.TRADE_DATE >= f.START_OK
  WHERE DAYOFWEEKISO(m.TRADE_DATE) BETWEEN 1 AND 5
),
missing AS (
  SELECT c.SYMBOL, TO_CHAR(c.TRADE_DATE,'YYYY-MM-DD') AS TRADE_DATE
  FROM cal c
  LEFT JOIN FEATURES_DAILY f
    ON f.SYMBOL=c.SYMBOL AND f.TRADE_DATE=c.TRADE_DATE
  WHERE f.TRADE_DATE IS NULL
)
SELECT * FROM missing ORDER BY SYMBOL, TRADE_DATE;