SELECT SYMBOL,
       COUNT(*) AS ROWS,
       TO_CHAR(MIN(TRADE_DATE),'YYYY-MM-DD') AS MIN_DATE,
       TO_CHAR(MAX(TRADE_DATE),'YYYY-MM-DD') AS MAX_DATE
FROM FEATURES_DAILY
GROUP BY SYMBOL
ORDER BY SYMBOL;