-- File: sql/20250826_031_create_holidays_nyse.sql
-- Title: Stage 1  NYSE Holidays (seed 2025)
USE DATABASE ZEN_MARKET;
USE SCHEMA FORECASTING;

CREATE TABLE IF NOT EXISTS HOLIDAYS_NYSE (
  HOLIDAY_DATE DATE PRIMARY KEY,
  NAME STRING
);

MERGE INTO HOLIDAYS_NYSE t
USING (
  SELECT TO_DATE('2025-01-01') AS D, 'New Year''s Day' UNION ALL
  SELECT TO_DATE('2025-01-20'), 'Martin Luther King Jr. Day' UNION ALL
  SELECT TO_DATE('2025-02-17'), 'Presidents'' Day' UNION ALL
  SELECT TO_DATE('2025-04-18'), 'Good Friday' UNION ALL
  SELECT TO_DATE('2025-05-26'), 'Memorial Day' UNION ALL
  SELECT TO_DATE('2025-06-19'), 'Juneteenth' UNION ALL
  SELECT TO_DATE('2025-07-04'), 'Independence Day' UNION ALL
  SELECT TO_DATE('2025-09-01'), 'Labor Day' UNION ALL
  SELECT TO_DATE('2025-11-27'), 'Thanksgiving Day' UNION ALL
  SELECT TO_DATE('2025-12-25'), 'Christmas Day'
) s
ON t.HOLIDAY_DATE = s.D
WHEN NOT MATCHED THEN INSERT (HOLIDAY_DATE, NAME) VALUES (s.D, s.NAME);