-- File: sql/20250826_050_grant_holidays_to_role.sql
-- Title: Stage 1  Grant SELECT on HOLIDAYS_NYSE to ZEN_PIPELINE_ROLE
GRANT SELECT ON TABLE ZEN_MARKET.FORECASTING.HOLIDAYS_NYSE TO ROLE ZEN_PIPELINE_ROLE;