CREATE TABLE IF NOT EXISTS MARKET_OHLCV_REJECTS (
  SYMBOL      STRING,
  TRADE_DATE  DATE,
  OPEN        NUMBER(18,6),
  HIGH        NUMBER(18,6),
  LOW         NUMBER(18,6),
  CLOSE       NUMBER(18,6),
  ADJ_CLOSE   NUMBER(18,6),
  VOLUME      NUMBER(38,0),
  SOURCE      STRING,
  REASON      STRING,
  LOAD_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);