DELETE FROM MARKET_OHLCV
USING (
  SELECT SYMBOL, TRADE_DATE, LOAD_TS,
         ROW_NUMBER() OVER (PARTITION BY SYMBOL, TRADE_DATE ORDER BY LOAD_TS DESC) AS RN
  FROM MARKET_OHLCV
) d
WHERE MARKET_OHLCV.SYMBOL=d.SYMBOL
  AND MARKET_OHLCV.TRADE_DATE=d.TRADE_DATE
  AND MARKET_OHLCV.LOAD_TS=d.LOAD_TS
  AND d.RN > 1;