WITH m AS (SELECT SYMBOL, TRADE_DATE FROM MARKET_OHLCV),
     f AS (SELECT SYMBOL, TRADE_DATE FROM FEATURES_DAILY),
     b AS (
       SELECT SYMBOL, DATEADD(day, 13, MIN(TRADE_DATE)) AS CUTOFF
       FROM FEATURES_DAILY
       GROUP BY SYMBOL
     ),
     missing AS (
       SELECT m.SYMBOL, m.TRADE_DATE
       FROM m
       JOIN b USING (SYMBOL)
       LEFT JOIN f ON f.SYMBOL = m.SYMBOL AND f.TRADE_DATE = m.TRADE_DATE
       WHERE m.TRADE_DATE > b.CUTOFF
         AND f.TRADE_DATE IS NULL
     )
SELECT COUNT(*) AS MISSING_AFTER_WARMUP FROM missing;