-- File: vscode_snowflake_starter/sql/20250825_023_create_forecast_daily.sql
-- Title: Stage 2  Create FORECAST_DAILY
CREATE TABLE IF NOT EXISTS FORECAST_DAILY (
  SYMBOL         STRING,
  TRADE_DATE     DATE,
  PREDICTION     STRING,
  PROB_UP        NUMBER(6,4),
  PROB_DOWN      NUMBER(6,4),
  CONFIDENCE     NUMBER(6,4),
  MODEL_VERSION  STRING,
  NOTES          STRING,
  CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FORECAST_DAILY PRIMARY KEY (SYMBOL, TRADE_DATE)
);