-- File: vscode_snowflake_starter/sql/20250825_020_create_forecast_tables.sql
-- Title: Stage 2  Create FEATURES_DAILY & FORECAST_DAILY
-- Commit Notes:
-- - Idempotent CREATE IF NOT EXISTS; PK on (SYMBOL, TRADE_DATE).

CREATE TABLE IF NOT EXISTS FEATURES_DAILY (
  SYMBOL       STRING,
  TRADE_DATE   DATE,
  CLOSE        NUMBER(18,6),
  ADJ_CLOSE    NUMBER(18,6),
  RETURN_1D    NUMBER(18,8),
  RSI_14       NUMBER(18,6),
  ATR_14       NUMBER(18,6),
  SOURCE       STRING,
  LOAD_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FEATURES_DAILY PRIMARY KEY (SYMBOL, TRADE_DATE)
);

CREATE TABLE IF NOT EXISTS FORECAST_DAILY (
  SYMBOL         STRING,
  TRADE_DATE     DATE,
  PREDICTION     STRING,
  PROB_UP        NUMBER(6,4),
  PROB_DOWN      NUMBER(6,4),
  CONFIDENCE     NUMBER(6,4),
  MODEL_VERSION  STRING,
  NOTES          STRING,
  CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FORECAST_DAILY PRIMARY KEY (SYMBOL, TRADE_DATE)
);