-- File: vscode_snowflake_starter/sql/20250825_022_create_features_daily.sql
-- Title: Stage 2  Create FEATURES_DAILY
CREATE TABLE IF NOT EXISTS FEATURES_DAILY (
  SYMBOL       STRING,
  TRADE_DATE   DATE,
  CLOSE        NUMBER(18,6),
  ADJ_CLOSE    NUMBER(18,6),
  RETURN_1D    NUMBER(18,8),
  RSI_14       NUMBER(18,6),
  ATR_14       NUMBER(18,6),
  SOURCE       STRING,
  LOAD_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FEATURES_DAILY PRIMARY KEY (SYMBOL, TRADE_DATE)
);