WITH rng AS (
  SELECT SYMBOL, MIN(TRADE_DATE) AS MIN_DATE, MAX(TRADE_DATE) AS MAX_DATE
  FROM MARKET_OHLCV GROUP BY SYMBOL
),
cal AS (
  SELECT r.SYMBOL,
         DATEADD(day, seq4(), r.MIN_DATE) AS D
  FROM rng r, TABLE(GENERATOR(ROWCOUNT => 20000))
  WHERE DATEADD(day, seq4(), r.MIN_DATE) <= r.MAX_DATE
    AND DAYOFWEEKISO(DATEADD(day, seq4(), r.MIN_DATE)) BETWEEN 1 AND 5
),
missing AS (
  SELECT c.SYMBOL, TO_CHAR(c.D,'YYYY-MM-DD') AS TRADE_DATE
  FROM cal c
  LEFT JOIN HOLIDAYS_NYSE h ON h.H_DATE = c.D
  LEFT JOIN MARKET_OHLCV m  ON m.SYMBOL=c.SYMBOL AND m.TRADE_DATE=c.D
  WHERE h.H_DATE IS NULL      -- exclude full-day holidays
    AND m.TRADE_DATE IS NULL  -- truly missing business day
)
SELECT * FROM missing ORDER BY SYMBOL, TRADE_DATE;