#!/bin/sh
set -e

echo "🔐 CI Signature Check"

# Create audit directory
AUDIT_DIR="audit_exports/daily/$(date +%Y%m%d_%H%M%S)"
mkdir -p "${AUDIT_DIR}"

# Calculate actual hash
ACTUAL_HASH=$(sha256sum .gitlab-ci.yml | cut -d' ' -f1)
echo "Actual .gitlab-ci.yml hash: ${ACTUAL_HASH}"

CURRENT_DATE="$(date '+%Y-%m-%d %H:%M:%S UTC')"

if [ -n "$CI_SIGNATURE" ]; then
    echo "Expected hash: ${CI_SIGNATURE}"
    if [ "$ACTUAL_HASH" != "$CI_SIGNATURE" ]; then
        echo "❌ ERROR: CI signature mismatch — potential drift detected"
        echo "Update CI_SIGNATURE variable if this change is intentional"
        echo "FAIL" > "${AUDIT_DIR}/CI_SIGNATURE_STATUS"
        
        cat > "${AUDIT_DIR}/CI_SIGNATURE.md" << EOF
# CI Signature Check - FAILED
**Date**: ${CURRENT_DATE}
**Repository**: ${CI_PROJECT_PATH}
**Project ID**: ${CI_PROJECT_ID}

## Signature Verification
- **Status**: ❌ FAILED
- **Expected Hash**: ${CI_SIGNATURE}
- **Actual Hash**: ${ACTUAL_HASH}
- **Drift Detected**: YES

## Action Required
Update CI_SIGNATURE variable if this change is intentional.

---
Generated by ZenMarket AI QA Guardrails
EOF
        exit 1
    fi
    
    echo "✅ CI signature verified"
    echo "PASS" > "${AUDIT_DIR}/CI_SIGNATURE_STATUS"
    
    cat > "${AUDIT_DIR}/CI_SIGNATURE.md" << EOF
# CI Signature Check - PASSED
**Date**: ${CURRENT_DATE}
**Repository**: ${CI_PROJECT_PATH}
**Project ID**: ${CI_PROJECT_ID}

## Signature Verification
- **Status**: ✅ PASSED
- **Expected Hash**: ${CI_SIGNATURE}
- **Actual Hash**: ${ACTUAL_HASH}
- **Drift Detected**: NO

---
Generated by ZenMarket AI QA Guardrails
EOF
    
else
    echo "⚠️  WARNING: CI_SIGNATURE not set - skipping verification"
    echo "Set CI_SIGNATURE=${ACTUAL_HASH} to enable protection"
    echo "SKIP" > "${AUDIT_DIR}/CI_SIGNATURE_STATUS"
    
    cat > "${AUDIT_DIR}/CI_SIGNATURE.md" << EOF
# CI Signature Check - SKIPPED
**Date**: ${CURRENT_DATE}
**Repository**: ${CI_PROJECT_PATH}
**Project ID**: ${CI_PROJECT_ID}

## Signature Verification
- **Status**: ⚠️  SKIPPED (CI_SIGNATURE not set)
- **Current Hash**: ${ACTUAL_HASH}
- **Recommendation**: Set CI_SIGNATURE=${ACTUAL_HASH} to enable protection

---
Generated by ZenMarket AI QA Guardrails
EOF
fi

echo "📄 Evidence file: ${AUDIT_DIR}/CI_SIGNATURE.md"
cat "${AUDIT_DIR}/CI_SIGNATURE.md"